version: "3.8"

services:
    laravel:
        build:
            context: .
        ports:
            - "8000:8000" # Map port 8000 of the host to the container
        volumes:
            - .:/app # Mount the current directory into the container
        environment:
            DB_CONNECTION: mysql
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: breeze_project
            DB_USERNAME: root
            DB_PASSWORD: ""
        depends_on:
            - mysql # Ensure MySQL starts before Laravel
        command: >
            bash -c "php artisan migrate && php artisan serve --host=0.0.0.0 --port=8000"
    mysql:
        image: mysql:8.0
        container_name: mysql
        ports:
            - "3306:3306" # Expose MySQL on port 3306
        environment:
            MYSQL_ROOT_PASSWORD: "" # No password for the root user
            MYSQL_DATABASE: breeze_project # Database to create
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        volumes:
            - mysql_data:/var/lib/mysql # Persist database data

volumes:
    mysql_data:
